name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - backend

jobs:
  build-and-push-backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Backend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/rental_fastapi:latest ./backend

      - name: Push Backend Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rental_fastapi:latest
